apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repos/git/cluster-repository.yaml
  - repos/helm/bitnami.yaml
  - repos/helm/bjw-s.yaml
  - repos/helm/cloudnative-pg.yaml
  - vars/ks.yaml
  - postgres/ks.yaml
  - payload-cms/ks.yaml