apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenant-bzweb-trial
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/basel
  prune: true
  sourceRef:
    kind: GitRepository
    name: tenant-bzweb-trial
  decryption:
    provider: sops
    secretRef:
      name: sops-age