apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tenant-bzweb-trial
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/freezedried-ai/tenant-bzweb-trial
  ref:
    branch: main
  secretRef:
    name: flux-gitea-token